//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWinform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonTextData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonTextData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorWinform.ButtonTextData", typeof(ButtonTextData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Calculator.
        /// </summary>
        internal static string AdvancedCalculatorText {
            get {
                return ResourceManager.GetString("AdvancedCalculatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Calculator.
        /// </summary>
        internal static string BasicCalculatorText {
            get {
                return ResourceManager.GetString("BasicCalculatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        internal static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Calculator:
        ///        ///
        ///        ///
        ///        ///1. Advanced Calculator Function
        ///        ///i.  Trignometric Function(Tan , Sin , Cos)
        ///        ///ii.  Logarithmic Function(Log)
        ///        ///iii.  Exponential / power Function( ^ )
        ///        ///iv.  Arithematic Operations (Add , subtract , multiplication , division, percentage)
        ///        ///v.  CE (Clear Entry) , C ( Clear ) , &amp;lt;- ( Backspace)
        ///        ///vi. Unary Operator ( ± )
        ///        ///vii. Square Root ( √ )
        ///        ///viii. Decimal Point ( . ) 
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M+.
        /// </summary>
        internal static string MemoryAdd {
            get {
                return ResourceManager.GetString("MemoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string MemoryClear {
            get {
                return ResourceManager.GetString("MemoryClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory :.
        /// </summary>
        internal static string MemoryLabel {
            get {
                return ResourceManager.GetString("MemoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR.
        /// </summary>
        internal static string MemoryRead {
            get {
                return ResourceManager.GetString("MemoryRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        internal static string MemoryStore {
            get {
                return ResourceManager.GetString("MemoryStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-.
        /// </summary>
        internal static string MemorySubtract {
            get {
                return ResourceManager.GetString("MemorySubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing saved in the Memory...
        /// </summary>
        internal static string MemoryValue {
            get {
                return ResourceManager.GetString("MemoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
    }
}
